qualityConfig:
  application:
    name: antibots.portal.frontend
    owner: Commerce Launch Fairness
    team: Commerce Launch Fairness
    email: Lst-gc-cdn-antibots.admin@nike.com
    costcenter: 104420
    organization: Web Eng - nike.com Cloud Capability
    domain: gc-cdn-antibots