@Library('cicd-pipeline') _

def app = 'webb-portal-frontend'
def teamPrefix = 'gcantibots'
def config = [
    buildFlow: [
            PULL_REQUEST    : ['Build', 'Compile'],
            DEVELOPMENT     : ['Containerize', 'Container Test'],
            RELEASE         : ['Containerize', 'Container Test']
    ],
    branchMatcher: [ RELEASE: ['main'], DEVELOPMENT: ['^(?!main$).*$']],
    notify: [
        slack: [
            channel: "#cicd-deploy",
            onCondition: ['any']
        ]
    ],
    tags: [
        'Name': 'webb-portal-frontend',
        'costcenter': '161961',
        'classification': 'sliver',
        'email': 'Lst-gc-cdn-antibots.admin@nike.com',
        'owner': 'gc-cdn-antibots',
        'nike-department': 'platform engineering - gc launch',
        'nike-domain': 'gc-cdn-antibots',
        'nike-application': 'webb-portal-frontend',
        'nike-distributionlist': 'Lst-gc-cdn-antibots.admin@nike.com',
        'nike-owner': 'frank.zhao@nike.com',
    ],
    // qma: [
    //     configFile: 'quality-config.yaml'
    // ],
    container: [
        name: app,
        group: teamPrefix, // name and group are used to find the ecr on aws, so the ecr name need to match with `${name}/${group}`
        dockerFileName: (params.Flow == 'RELEASE') ? 'Dockerfile.prod' : 'Dockerfile.test',
        // If you want to apply a particular tag
        // releaseTag: "release",
    ],
    containerTest: [
        //containerTest provides a genericBuild step that can be used to validate the container
        cmd: 'echo \"my docker container tag is ${DOCKER_CONTAINER}\"',
    ],
    // cache: [
    //     strategy: 'mountAsDockerVolume',
    //     tool: 'gradle',
    // ],
    // build: [
    //     image: 'gradle:6.8.3-jdk15',
    //     cmd: 'gradle clean build',
    // ],
    // pra: [
    //     sdbPath: "app/cdservice/a.bmx.scm",
    //     userNameKey: "github_username",
    //     passwordKey: "github-pat",
    // ],
    deploymentEnvironment : [
        test : [
            agentLabel: 'china',
            deployFlow: [
                    DEVELOPMENT : ["Publish To ECR","Deploy"],
                    RELEASE : ["Publish To ECR","Deploy"],
            ],
            signalfx: [
                app: app,
                sdbPath: "shared/bmx-shared/jenkins/signalfx",
                sdbKey:"access-token",
            ],
            cloudEnvironment: "test",
            deploy: [
                    awsRole: "arn:aws-cn:iam::439314357471:role/gcantibots-BrewmasterEcsRole",
                    accountId: "439314357471",
                    region: "cn-northwest-1",
                    launchType: 'EC2',
                    clusterName: "webb-portal-frontend-cluster-test",
                    securityGroups: "sg-068ad6058ed04d8c9",
                    subnets: 'subnet-0da1766492b750893,subnet-06da179024e04fbbd,subnet-05abf20a7b7d9cfac',
                    taskExecutionRoleArn: "arn:aws-cn:iam::439314357471:role/gcantibots-TaskExecutionRole",
                    vpcId: 'vpc-0f9779e69a780c25e',
                    taskCpu: 1024,
                    appContainerCpu: 1024,
                    taskMemory: 1024,
                    appContainerMemory: 1024,
                    healthCheckPath: '/',
                    healthCheckPort: '3000',
                    containerPort: '3000',
                    listenerArn: 'arn:aws-cn:elasticloadbalancing:cn-northwest-1:439314357471:listener/app/webbFrontendALB/b15b14cde0a72a20/6c6268f9c59d0b6e',
                    listenerRulePriority: 1,
                    containerDesiredCount: 1,
                    // useSplunkTaskDriver: true,
                    // splunkToken: 'e8a2c4e9-2df8-4234-8b3d-b24dc733ce42',
                    // splunkIndex: "np-anti-bots",
                    // splunkUrl: "https://gcsplunk-hec.nike.com:443",
                    // splunkFormat: 'json',
                    targetGroupArn: 'arn:aws-cn:elasticloadbalancing:cn-northwest-1:439314357471:targetgroup/Webb-F-Front-NN4R8JXKLSV4/f101dd0b819bfb5d',
                    // pollInterval: 15000,
//                    If using custom stack name
//                    stackName: "${teamPrefix}-${app}-${env.BRANCH_NAME}-test",
//                    If using custom template
//                    cloudFormationTemplate: "ecs-service-template.yaml",
//                    parameters: [
//                    ],
            ],
            notify: [
                confirmDeploy: [
                    message    : "Waiting to deploy. Confirm Deploy",
                    slack      : [
                        channel: "#cicd-deploy",
                        color      : "#7CFC00",
                    ],
                    waitTime   : 120,
                ],
                deployComplete: [
                    message    : "DEPLOY COMPLETE Yeeeeeyyyyyy",
                    slack      : [
                        channel: "#cicd-deploy",
                        color      : "#7CFC00",
                    ],
                ],
                slack: [
                    channel: "#cicd-deploy",
                    waitTime: 90,
                    onCondition: ['deploy', 'deployComplete']
                ]
            ],
            userConfirmation: [
                deploy: [
                    proceedWhenNoAction: true,
                    waitTime: 2,
                    channel: "#cicd-deploy",
                ]
            ],
            tags: [
                    'nike-environment': 'test'
            ],
        ],
        prod : [
            agentLabel: 'china',
            deployFlow: [
                    DEVELOPMENT : ["Publish To ECR","Deploy"],
                    RELEASE : ["Publish To ECR","Deploy"],
            ],
            signalfx: [
                app: app,
                sdbPath: "shared/bmx-shared/jenkins/signalfx",
                sdbKey:"access-token",
            ],
            cloudEnvironment: "prod",
            deploy: [
                    awsRole: "arn:aws-cn:iam::439413396736:role/gcantibots-BrewmasterEcsRole",
                    accountId: "439413396736",
                    region: "cn-northwest-1",
                    launchType: 'EC2',
                    clusterName: "webb-portal-frontend-cluster-prod",
                    securityGroups: "sg-05dd79bfe6d170e26",
                    subnets: 'subnet-0b23b05edb4035d28,subnet-054062238d2327b0e,subnet-07b7c0ab40a91ae55',
                    taskExecutionRoleArn: "arn:aws-cn:iam::439413396736:role/gcantibots-TaskExecutionRole",
                    vpcId: 'vpc-01472d21bb792d03e',
                    taskCpu: 1024,
                    appContainerCpu: 1024,
                    taskMemory: 1024,
                    appContainerMemory: 1024,
                    healthCheckPath: '/',
                    healthCheckPort: '3000',
                    containerPort: '3000',
                    listenerArn: 'arn:aws-cn:elasticloadbalancing:cn-northwest-1:439413396736:listener/app/webbFrontendALB/f7cc8db7e9da04fb/bf74f91102aafa3c',
                    listenerRulePriority: 1,
                    containerDesiredCount: 1,
                    // useSplunkTaskDriver: true,
                    // splunkToken: 'e8a2c4e9-2df8-4234-8b3d-b24dc733ce42',
                    // splunkIndex: "np-anti-bots",
                    // splunkUrl: "https://gcsplunk-hec.nike.com:443",
                    // splunkFormat: 'json',
                    targetGroupArn: 'arn:aws-cn:elasticloadbalancing:cn-northwest-1:439413396736:targetgroup/Webb-F-Front-WYNPBGKQL9DN/b2d057173e5e4aee',
                    // pollInterval: 15000,
//                    If using custom stack name
//                    stackName: "${teamPrefix}-${app}-${env.BRANCH_NAME}-test",
//                    If using custom template
//                    cloudFormationTemplate: "ecs-service-template.yaml",
//                    parameters: [
//                    ],
            ],
            notify: [
                confirmDeploy: [
                    message    : "Waiting to deploy. Confirm Deploy",
                    slack      : [
                        channel: "#cicd-deploy",
                        color      : "#7CFC00",
                    ],
                    waitTime   : 120,
                ],
                deployComplete: [
                    message    : "DEPLOY COMPLETE Yeeeeeyyyyyy",
                    slack      : [
                        channel: "#cicd-deploy",
                        color      : "#7CFC00",
                    ],
                ],
                slack: [
                    channel: "#cicd-deploy",
                    waitTime: 90,
                    onCondition: ['deploy', 'deployComplete']
                ]
            ],
            userConfirmation: [
                deploy: [
                    proceedWhenNoAction: true,
                    waitTime: 2,
                    channel: "#cicd-deploy",
                ]
            ],
            tags: [
                    'nike-environment': 'prod'
            ],
        ],
    ]
]

ecsDeployPipeline(config)